from aiogram.dispatcher.filters.state import StatesGroup, State


class FSMsokolov(StatesGroup):
    number = State()
    date = State()
    time_start = State()
    audio = State()
    name_worker = State()
    number_workers = State()
    number_clients = State()
    worker_job = State()
    worker_substrate = State()
    worker_friendliness = State()
    worker_service = State()

class FSMmts(StatesGroup):
    number = State()
    date = State()
    time_start = State()
    rezgim = State()
    number_workers = State()
    number_clients = State()
    name_worker = State()
    describe_worker = State()
    resume = State()
    audio = State()
    photo1 = State()
    photo2 = State()

class FSMgate31(StatesGroup):
    number = State()
    date = State()
    audio = State()
    photo = State()
    operator_name = State()
    outside = State()
    inside = State()
    describe_worker = State()
    product_appearance = State()
    spoon = State()
    worker_count = State()
    client_count = State()
    consultant_friendliess = State()
    consultant_fitting = State()
    consultant_products = State()
    consultant_cash = State()
    consultant_payment = State()
    consultant_same = State()
    duty_name = State()
    consultant_product_count = State()
    consultant_closeness = State()
    cashier_name = State()
    cashier_friendliess = State()
    cashier_paper = State()
    cashier_handed = State()
    general_impression = State()
    worker_friendliess = State()
    consultant_activity = State()
    worker_competence = State()
    worker_persistence = State()
    worker_time = State()
    return_desire = State()
    back_name = State()
    back_friendliess = State()
    back_main = State()

class FSMirbis(StatesGroup):
    number = State()
    date = State()
    audio = State()
    photo = State()
    operator_name = State()
    azs_name = State()
    column = State()
    territory = State()
    sanuzel = State()
    situation = State()
    object_tips = State()
    main_problem = State()
    filler_job = State()
    fill = State()
    fill_tips = State()
    fill_problem = State()
    cashier_appearance = State()
    cashier_job = State()
    cashier_tips = State()
    cashier_problem = State()

class FSMmuztorg(StatesGroup):
    date = State()
    audio = State()
    photo1 = State()
    photo2 = State()
    worker_count = State()
    client_count = State()
    sex = State()
    age = State()
    worker_3_minute = State()
    worker_name = State()
    worker_appearance = State()
    hall_appearance = State()
    consultant_friendly = State()
    other_consultant = State()
    general_impression = State()
    workers_friendly = State()
    consultant_activity = State()
    worker_competence = State()

class FSMkastorama(StatesGroup):
    date = State()
    time = State()
    audio = State()
    photo = State()
    parking_clear = State()
    parking_free = State()
    carts = State()
    toilets_clear = State()
    zamki = State()
    santehnika = State()
    info = State()
    cart_alley = State()
    cash_number = State()
    cashier_name = State()
    queue_number = State()
    queue_time = State()
    cashier_appearance = State()
    worker_job_client = State()
    cashier_correctly = State()
    cashier_barcode = State()
    cashier_solvency = State()
    cashier_change = State()
    cashier_job_user = State()
    cashier_positive = State()
    cashier_help = State()
    cashier_benevolence = State()

class FSMsubway(StatesGroup):
    number = State()
    date = State()
    audio = State()
    photo = State()
    operator_name = State()
    azs_name = State()
    column = State()
    cashier_name = State()
    queue_number = State()
    queue_time = State()
    cashier_appearance = State()
    worker_job_client = State()
    cashier_correctly = State()
    cashier_barcode = State()
    cashier_solvency = State()
    cashier_job = State()
    cashier_tips = State()
    cashier_problem = State()
    cashier_friendliess = State()
    cashier_paper = State()
    cashier_handed = State()
    general_impression = State()
    worker_friendliess = State()
    consultant_activity = State()
